name: resead
channels:
  - conda-forge
dependencies:
  - bottleneck=1.3.7
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - geopy=2.3.0
  - h5py=3.9.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - ipykernel=6.25.0
  - ipython=8.14.0
  - jupyterlab=4.0.3
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - matplotlib=3.7.2
  - netcdf4=1.6.4
  - networkx=3.1
  - numpy=1.25.2
  - omegaconf=2.3.0
  - pandas=2.0.3
  - pyyaml=6.0
  - python=3.9.16
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - tensorboard=2.11.2
  - tensorflow=2.11.1
  - tensorflow-gpu=2.11.1
  - wandb=0.15.8
  - xarray=2023.7.0
  - coverage=7.2.7
  - pip:
    - livelossplot==0.5.5
    - spektral==1.3.0
